services:
    redis:
        container_name: redis
        image: redis
        command: ["redis-server"]
        hostname: redis
        ports:
        - 6379:6379
    db:
        image: mysql
        platform: linux/amd64
        restart: always
        ports:
        - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
        - ./mysqldata:/var/lib/mysql:rw,delegated
    db-tests:
        image: mysql
        restart: always
        container_name: integration-tests-prisma
        ports:
        - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: prisma
            MYSQL_DATABASE: tests

